module.exports = Object.freeze({
  API_URL: {
    TOKEN: "/token",
    CLOSE: '/close',
    PUSH_NOTIFICATION: '/push-notification',
    GET_NOTIFICATIONS: '/get-notifications',
    GET_LEVEL_BY_SCORE: '/get-level-by-score',
    EMAIL_SEND: '/email-send',
    LOGIN: '/login',
    VALIDATE_USERNAME: '/validate-username',
    SIGNUP: '/sign-up',
    VERIFIED: '/verified',
    RESET: '/reset',
    UPDATE_USER: '/update-user',
    USER_INSERVICE: '/user-inservice',
    UPDATE_PROFILE: '/update-profile',
    UPDATE_DEVICE_TOKEN: '/update-device-token',
    UPDATE_NOTIFICATION: '/update-notification',
    UNSEEN_NOTIFICATION: '/unseen-notification',
    FORGOT_PASSWORD: '/forgot-password',
    GET_SCENARIOS: '/get-all-scenarios',
    GET_SCENARIO_BY_ID: '/get-scenario-by-id',
    GET_SCENARIO_BY_CATEGORY: '/get-scenario-by-category',
    GET_SCENARIO_CATEGORIES_AND_COUNTS: '/get-scenario-categories-count',
    ADD_SCENARIO: '/add-scenario',
    UPDATE_SCENARIO: '/update-scenario',
    DELETE_SCENARIO: '/delete-scenario',
    DUPLICATE_SCENARIO: '/duplicate-scenario',
    DUPLICATE_SCENE: '/duplicate-scene',
    ADD_USER_SCENARIO: '/add-user-scenario',
    GET_SCENARIO_BY_USER_ID: '/get-scenario-by-user-id',
    GET_SCENARIO_DATA_BY_ID: '/get-scenario-data-by-id',
    ADD_SCENE: '/add-scene',
    UPDATE_SCENE: '/update-scene',
    DELETE_SCENE: '/delete-scene',
    GET_MAIN_SCENE_BY_SCENARIO_ID: '/get-main-scene-by-scenario-id',
    GET_SCENES_BY_SCENARIO_ID: '/get-all-scene-by-scenario',
    GET_SCENES_DATA_BY_ID: '/get-scene-data-by-id',
    ADD_CHARACTER: '/add-character',
    UPDATE_CHARACTER: '/update-character',
    DELETE_CHARACTER: '/delete-character',
    GET_CHARACTERS: '/get-all-characters',
    GET_CHARACTER: '/get-character-by-id',
    ADD_DIALOG: '/add-dialog',
    UPDATE_DIALOG: '/update-dialog',
    DELETE_DIALOG: '/delete-dialog',
    GET_DIALOGS: '/get-all-dialogs',
    GET_DIALOG: '/get-dialog-by-id',
    DELETE_DIALOG_SCENE_ID: '/delete-dialog-by-scene-id',
    ADD_ITEM: '/add-item',
    UPDATE_ITEM: '/update-item',
    DELETE_ITEM: '/delete-item',
    GET_ITEMS: '/get-all-items',
    GET_ITEMS_IMAGES: '/get-all-items-with-image',
    GET_ITEM: '/get-item-by-id',
    ADD_LEVEL: '/add-level',
    UPDATE_LEVEL: '/update-level',
    DELETE_LEVEL: '/delete-level',
    GET_BY_ID: '/get-level-by-id',
    GET_BADGE_BY_USER_ID: '/get-badge-by-user-id',
    GET_ALL_LEVEL: '/get-all-levels',
    GET_ALL_BADGE: '/get-all-badges',
    ADD_USER_BADGES: '/add-user-badges',
    UPDATE_SCENARIO_RANDOMLY: '/update-scenario-randomly',
    GET_INITIAL_USERS: '/get-initial-users',
    ADD_QUIZ: '/add-quiz',
    UPDATE_QUIZ: '/update-quiz',
    DELETE_QUIZ: '/delete-quiz',
    GET_QUIZ: '/get-quiz-by-id',
    GET_QUIZZES: '/get-all-quiz',
    ADD_QUESTION: '/add-question',
    GET_QUESTION: '/get-question-by-id',
    GET_ALL_QUESTIONS: '/get-all-questions',
    DELETE_QUESTION: '/delete-question',
    UPDATE_QUESTION: '/update-question',
    GET_ALL_QUESTIONS_BY_ID: '/get-all-questions-by-quiz-id',
    ADD_AVATAR: '/add-avatar',
    GET_USER_CURRENCY: '/get-users-currency',
    GET_USER_BY_ID: '/get-user-by-id',
    GET_INTRODUCTORY_QUIZ : '/get-introductory-quiz',
    UPDATE_INTRODUCED_USER : '/update-introduced-user',
    UPDATE_CURRENCY: '/update-currency',
    GET_ALL_AVATARS: '/get-all-avatars',
    GET_AVATAR: '/get-avatar-by-id',
    DELETE_AVATAR: '/delete-avatar',
    UPDATE_AVATAR: '/update-avatar',
    ADD_USER_ITEMS: '/add-user-items',
    GET_AVATAR_BY_ID: '/get-avatars-by-id',
    GET_AVATAR_BY_USER_ID: '/get-avatar-by-user-id',
    GET_AVATARS: '/get-avatars',
    GET_PUBLISH_QUIZZES: '/get-publish-quiz',
    USER_WEEKLY_SCORE: '/add-weekly-score',
    GET_USER_WEEKLY_SCORE: '/get-weekly-score-by-id',
    GET_USER_HISTORY: '/get-history-by-id',
    GET_ALL_SCENES: '/get-all-scenes',
    ADD_BACKGROUND: '/add-background',
    UPDATE_BACKGROUND: '/update-background',
    GET_ALL_BACKGROUNDS: '/get-all-backgrounds',
    DELETE_BACKGROUND: '/delete-background',
    GET_BACKGROUND_BY_ID: '/get-background-by-id',
    USER_RANK_API: '/user-rank'
  },
  HTTP: {
    SUCCESS: {
      CODE: 200,
      MESSAGE: 'Success'
    },
    INTERNAL_SERVER_ERROR: {
      CODE: 500,
      MESSAGE: 'Internal Server Error'
    },
    UNPROCESSABLE_ENTITY: {
      CODE: 422,
      MESSAGE: 'Unprocessable Entity'
    }
  },
  MESSAGES: {
    UNAUTHORIZE: 'Sorry!! You are not authorized to access.',
    WELCOME: 'Welcome to EMS Adventure Server.',
    SCENE_NOT_AVAILABLE: 'Selected scene is not available or corrupted.',
    UPLOAD_CHARACTER: 'upload character',
    ADD_BADGES: 'Add Badges',
    ADD_ITEMS: 'Add Items'
  },
  FAILMESSAGES: {
    LOGIN: 'Login Failed!',
    LOGIN_MESSAGE: 'Username or password is incorrect',
    STATUS: false,
    SIGN_UP: 'Sign Up Failed!',
    SIGN_UP_MESSAGE: 'Email is already registered.',
    UNVERIFIED_MESSAGE: 'Please verify your account first.'
  }
});
